
# model with balance
```{r}
library(ISLR2)

# View(Default)

glm.balance = glm(default~balance, data=Default, family = binomial)

summary(glm.balance)
```
## prediction
```{r}
new_data = data.frame(balance=1000)
```


```{r}
t =  predict(glm.balance, newdata = new_data)

exp(t)/(1+exp(t))
```


```{r}
predict(glm.balance, newdata = new_data, type="response")
```
# model with student
```{r}
glm.student = glm(default~student, data = Default, family = binomial)

summary(glm.student)
```
# model with all variables
```{r}
library(ISLR2)
glm.all = glm(default~., data = Default, family = "binomial")

summary(glm.all)
```
## prediction
```{r}
new_data = data.frame( student="Yes", balance = 1500, income=40000)

predict(glm.all, newdata = new_data, type= 'response')

```


## boxplot
```{r}
boxplot(Default$income)
boxplot(Default$balance)
```

```{r}
boxplot(Default$balance~Default$student)
```

# confusion matrix
```{r}
library(ISLR2)

# logistic regression model
glm.all = glm(default~., data = Default, family = "binomial")

# get predicted probability
prob = predict(glm.all, newdata = Default, type = 'response')

# get predicted y values
pred = rep('No', nrow(Default))
pred[prob>0.5] = 'Yes'

# confusion matrix
table(pred, Default$default)
```


```{r}
N = nrow(Weekly)
train.set = Weekly[1:900,]
test.set = Weekly[901:N, ]

# logistic regression
lr.model = glm(Direction~Lag2, data = train.set, family = binomial)

# get predicted probability
prob.test = predict(lr.model, newdata = test.set, type = 'response')

# get predicted y values
pred.test = rep('Down', nrow(test.set))
pred.test[prob.test>0.5] = 'Up'

# confusion matrix
tab.test = table(pred.test, test.set$Direction)

# the overall fraction of correct predictions
sum(diag(tab.test))/sum(tab.test)


```












