---
title: "R Notebook"
output: html_notebook
---
```{r}
library(ISLR2)
dim(Default)


dat.y = Default[Default$default == 'Yes',]
dat.n = Default[Default$default == 'No',]

dat = rbind(dat.y[1:5, ], dat.n[1:4, ])
dat = dat[,c(1,3)]

```
#Pi 
# Pi 
```{r}
pi_yes = mean(dat$default == 'Yes')
pi_no = mean(dat$default == 'No')
print(pi_yes)
print(pi_no)
```


# mu
```{r}
mu_yes = mean(dat[dat$default == 'Yes',2])
mu_no = mean(dat[dat$default == 'No',2])
mu_yes
mu_no
```

# sigma
```{r}
x1 = dat[dat$default =='Yes',2]
x0 = dat[dat$default =='No',2]

sigma = sum(x1-mu_yes)^2
sigma
```


```{r}
library(MASS)
lda.all = lda(default~., data = Dault)
lda.pre = predict(lda.all,newdata = Default)
pred.prob = lda.pre$posterior[,2]

pred
```

#QDA
```{r}
library(MASS)



qda.all = lda(default~., data = Default)
qda.all
qda.pred = predict(lda.all, newdata = Default)
```

# overall overate (0.027) (31+239)/10000
```{r}
table(qda.pred$class, Default$default)

```

```{r}
library (e1071)
naiveBayes(default ~ ., data=Default )
nb.class = predict(nb.fit, Default)
```